Syntax issue on string #61
IBM/prediction-using-watson-machine-learning pull request #18
Opened 2019-02-25 13:07 UTC by kant

* plus some minor fixes on punctuation.

2019-02-25 13:28 UTC, scottdangelo requested changes

2019-02-25 13:28 UTC, scottdangelo commented on README.md
> +* Select the Spark runtime with Python 3.5.
I don't like this syntax. Yes, some might argue that it is correct, but it looks like the patch version is missing for the form `3.5.x`

2019-02-25 13:28 UTC, scottdangelo commented on README.md
> +* Enter your Watson Machine Learning credentials in the cell after `Action: Enter your Watson Machine Learning service instance credentials here.`.
same as above.

2019-04-11 14:45 UTC, stevemart commented
We're archiving this repo, please see https://github.com/IBM/monitor-wml-model-with-watson-openscale as an alternative

2019-04-11 14:45 UTC, closed without merging